openapi: 3.0.1
info:
  description: Kintone REST API
  version: 1.0.0
  title: Kintone REST API
paths:
  /app/acl.json:
    get:
      parameters:
        - in: query
          name: app
          schema:
            type: string
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  rights:
                    items:
                      $ref: '#/components/schemas/Right'
                    type: array
                  revision:
                    format: long
                    type: string
                type: object
components:
  schemas:
    Right:
      properties:
        recordImportable:
          type: boolean
        appEditable:
          type: boolean
        recordExportable:
          type: boolean
        recordAddable:
          type: boolean
        recordViewable:
          type: boolean
        recordEditable:
          type: boolean
        includeSubs:
          type: boolean
        recordDeletable:
          type: boolean
        entity:
          properties:
            code:
              type: string
            type:
              enum:
                - USER
                - ORGANIZATION
                - GROUP
                - CREATOR
              type: string
          type: object
      type: object
